.PHONY: clean All

All:
	@echo "----------Building project:[ func_class - Debug ]----------"
	@cd "func_class" && "$(MAKE)" -f  "func_class.mk"
clean:
	@echo "----------Cleaning project:[ func_class - Debug ]----------"
	@cd "func_class" && "$(MAKE)" -f  "func_class.mk" clean
