.PHONY: clean All

All:
	@echo "----------Building project:[ BinaryHeap - Debug ]----------"
	@"$(MAKE)" -f  "BinaryHeap.mk"
clean:
	@echo "----------Cleaning project:[ BinaryHeap - Debug ]----------"
	@"$(MAKE)" -f  "BinaryHeap.mk" clean
