.PHONY: clean All

All:
	@echo "----------Building project:[ reverse_Polish_notation - Debug ]----------"
	@"$(MAKE)" -f  "reverse_Polish_notation.mk"
clean:
	@echo "----------Cleaning project:[ reverse_Polish_notation - Debug ]----------"
	@"$(MAKE)" -f  "reverse_Polish_notation.mk" clean
