.PHONY: clean All

All:
	@echo "----------Building project:[ List - Debug ]----------"
	@"$(MAKE)" -f  "List.mk"
clean:
	@echo "----------Cleaning project:[ List - Debug ]----------"
	@"$(MAKE)" -f  "List.mk" clean
