.PHONY: clean All

All:
	@echo "----------Building project:[ maze - Debug ]----------"
	@"$(MAKE)" -f  "maze.mk"
clean:
	@echo "----------Cleaning project:[ maze - Debug ]----------"
	@"$(MAKE)" -f  "maze.mk" clean
