.PHONY: clean All

All:
	@echo "----------Building project:[ Stack - Debug ]----------"
	@"$(MAKE)" -f  "Stack.mk"
clean:
	@echo "----------Cleaning project:[ Stack - Debug ]----------"
	@"$(MAKE)" -f  "Stack.mk" clean
