.PHONY: clean All

All:
	@echo "----------Building project:[ Vector - Debug ]----------"
	@"$(MAKE)" -f  "Vector.mk"
clean:
	@echo "----------Cleaning project:[ Vector - Debug ]----------"
	@"$(MAKE)" -f  "Vector.mk" clean
